# Generated by Django 3.2.15 on 2025-01-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='product_in_order', to='foodcartapp.Product', verbose_name='продукт'),
        ),
    ]
