# Generated by Django 3.2.15 on 2025-02-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20250205_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Необработанный', 'необработанный'), ('Готовится', 'готовится'), ('Доставка', 'доставка'), ('Выполнен', 'выполнен')], max_length=14, verbose_name='Статус'),
        ),
    ]
