# Generated by Django 3.2.15 on 2025-02-05 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_auto_20250205_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='registrated_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
