# Generated by Django 3.2.15 on 2025-02-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_order_registrated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата создания заказа'),
        ),
    ]
