# Generated by Django 3.2.15 on 2025-02-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_auto_20250205_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payoment',
            field=models.CharField(choices=[('Наличкой', 'наличкой'), ('Переводом', 'переводом'), ('Картой', 'Картой')], default='Уточнить', max_length=9, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Необработанный', 'необработанный'), ('Готовится', 'готовится'), ('Доставка', 'доставка'), ('Выполнен', 'выполнен')], default='Необработанный', max_length=14, verbose_name='Статус'),
        ),
    ]
