# Generated by Django 3.2.15 on 2025-02-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0063_auto_20250205_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payoment',
            new_name='payment',
        ),
    ]
